default_language_version:
  python: python3.12
default_stages:
  - pre-commit
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude_types:
          - "markdown"
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--unsafe]
      - id: check-added-large-files
        args: ["--maxkb=10240"]
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-ast
      - id: check-json
        exclude: ".vscode/launch.json"
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-toml
      - id: debug-statements
      - id: detect-private-key
      - id: check-merge-conflict
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: forbid-new-submodules
      - id: mixed-line-ending

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.4 # Check for the latest version
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        args: ["-d", "relaxed"]
        language: system

  - repo: https://github.com/hadialqattan/pycln
    rev: v2.4.0
    hooks:
      - id: pycln
        entry: uv run pycln # Ensure it runs inside `uv`
        args: [--config=pyproject.toml]

  - repo: https://github.com/pycqa/docformatter
    rev: v1.7.5
    hooks:
      - id: docformatter
        language: python

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.17.0
    hooks:
      - id: pyupgrade
        entry: pyupgrade --py39-plus --keep-runtime-typing
        types:
          - python

  - repo: https://github.com/asottile/yesqa
    rev: v1.5.0
    hooks:
      - id: yesqa

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        language: system
        entry: uv run mypy .
        pass_filenames: false
        args:
          [
            --allow-subclassing-any,
            --allow-untyped-decorators,
            --check-untyped-defs,
            --follow-imports,
            "silent",
            --ignore-missing-imports,
            --implicit-reexport,
            --pretty,
            --python-version=3.9,
            --show-column-numbers,
            --show-error-codes,
            --strict,
            --warn-redundant-casts,
            --warn-return-any,
            --warn-unreachable,
            --warn-unused-configs,
            --warn-unused-ignores,
            --allow-untyped-calls,
          ]

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.42.0
    hooks:
      - id: markdownlint
        args: [--disable, MD013]
      - id: markdownlint-fix
        args: [--disable, MD013]
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.2
    hooks:
      - id: gitleaks
